### ISSUE TITLE
undefined: memguard.NewImmutableFromBytes

### ISSUE THREAD

**Issue by satoshisound** [mit-dci/dlc-oracle-go-samples#2]
Errors when running restapi example:
`crypto/keystore.go:14:15: undefined: memguard.NewImmutableFromBytes`
`crypto/keystore.go:27:29: cannot call non-function safeKey.Buffer (type *core.Buffer)`

Perhaps `memguard` has deprecated `NewImmutableFromByes`?

**Comment by gertjaap** [comment]
Fixed by #3
